name: Test CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Failing test
        run: |
          echo "Testing TraceFix"
          echo "ERROR: npm not found"
          exit 1
